version: '2'

services:
  app:
    image: 'meritwos:latest'
    build:
      context: .
    container_name: meritwos
    depends_on:
      - db
    environment:
      - DB_USER='meritwos'
      - DB_PASS='meritwos'
    ports:
      - 8080:8080

  db:
    image: 'mysql:latest'
    container_name: dbMysql
    volumes:
      - dbData:/var/lib/mysql
    environment:
      - MYSQL_DATABASE='meritwos'
      - MYSQL_USER='meritwos'
      - MYSQL_PASS='meritwos'
      - MYSQL_ROOT_PASSWORD='password'
    ports:
      - 3306:3306
volumes:
  dbData: